=== AI4quantum/maestro/bee-hive/bee_hive/agent_schema.json
{
  "$id": "https://github.com/i-am-bee/bee-hive/blob/main/bee-hive/agent_schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "beehive/Agent",
  "type": "object",
  "properties": {
    "apiVersion": {
      "type": "string",
      "description": "API version beehive/v1alpha1"
    },
    "kind": {
      "type": "string",
      "description": "must be Agent"
    },
    "metadata": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "agent name"
        },
        "labels": {
          "type": "object",
            "description": "agent labels, key: value pairs"
        },
        "namespace": {
          "type": "string",
          "description": "agent namespace"
        }
      },
      "required": ["name"]
    },
    "spec": {
      "type": "object",
      "properties": {
        "model": {
          "type": "string",
          "description": "agent name"
        },
        "framework": {
          "enum": [ "bee", "crewai", "langgraph" ],
          "default": "bee",
          "description": "Framework agent uses. Must be one of bee, crewai or langgraph. Default is bee"
        },
        "description": {
          "type": "string",
          "description": "agent description"
        },
        "instructions": {
          "type": "string",
          "description": "instructions for the agent"
        },
        "tools": {
          "type": "array",
          "description": "tool list of the agent",
          "items": {
            "type": "string"
          }    
        },
        "input": {
          "type": "string",
          "description": "instructions for the agent"
        },
        "output": {
          "type": "string",
          "description": "instructions for the agent"
        }
      },
      "required": ["model","instructions"]
    }
  }
}

=== AI4quantum/maestro/tests/schema/simple_agent.json
{
    "apiVersion": "beehive/v1alpha1",
    "kind": "Agent",
    "metadata": {
        "name": "test",
        "labels": {
            "app": "test-example"
        }
    },
    "spec": {
        "model": "meta-llama/llama-3-1-70b-instruct",
        "description": "this is a test",
        "tools": [
            "code_interpreter",
            "test"
        ],
        "instructions": "this is a test."
    }
}
